apiVersion: apps/v1
kind: Deployment
metadata:
  name: piuiudur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piuiudur
  template:
    metadata:
      labels:
        app: piuiudur
    spec:
      containers:
      - image: okteto.dev/piuiudur:latest
        name: piuiudur
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a9793630-175e-4c03-a0a6-58389b9367e6"
        - name: Vless_Path
          value: "/yswaGu23wer"
        - name: Vmess_UUID
          value: "03b7d3d4-f3a3-40a0-9121-9136ea2b284e"
        - name: Vmess_Path
          value: "/rsjifoeo3awe"
        - name: Share_Path
          value: "/v2link"
